### ISSUE TITLE
The `sessionId` property on SessionProvider should be optional

### ISSUE THREAD

**Issue by Vinnl** [inrupt/solid-ui-react#185]
### Search terms you've used
sessionId, sessionProvider, optional

### Bug description
The type definition of <SessionProvider> says that the `sessionId` prop is required, but solid-client-authn-browser can generate its own if none is passed.

### To Reproduce
1. Try to leave out the `seessionId` prop in e.g. VSCode.

### Expected result
No error.

### Actual result
A red squiggly line saying a prop is missing.

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 166.32 MB / 7.51 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0
  npmPackages:
    @inrupt/solid-client: ^0.6.1 => 0.6.1 
    @inrupt/solid-ui-react: ^1.5.1 => 1.5.1 
    @types/node: ^14.14.2 => 14.14.2 
    @types/react: ^16.9.53 => 16.9.53 
    @types/uuid: ^8.3.0 => 8.3.0 
    localforage: ^1.9.0 => 1.9.0 
    next: 9.5.5 => 9.5.5 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    sass: ^1.28.0 => 1.28.0 
    typescript: ^4.0.3 => 4.0.3 
    uuid: ^8.3.1 => 8.3.1 
  npmGlobalPackages:
    npm: 6.14.6
```

## Additional information

N/A

**Comment by nicolasmondada** [comment]
This has been fixed on #187
