### ISSUE TITLE
Custom loading component prop for CombinedDataProvider

### ISSUE THREAD

**Issue by julienmenten** [inrupt/solid-ui-react#294]
### Search terms you've used

- solid-ui-react custom loading component
- solid-ui-react CombinedDataProvider loading component

### Feature suggestion

When using the LogInButton combined with the CombinedDataProvider, the component fetches the data from the user's pod. However when loading, a message ("fetching data...") appears which is not stylable or changeable. I was wondering if that was already an option or if it would be an interesting feature to add for later. 

Current situation: 

1. Logging in
<img width="350" alt="Screenshot 2021-05-11 at 11 42 13" src="https://user-images.githubusercontent.com/43605864/117795763-c3606600-b24e-11eb-8493-41c2d219c13a.png">
2. Loading data
<img width="350" alt="Screenshot 2021-05-11 at 11 42 38" src="https://user-images.githubusercontent.com/43605864/117795026-12f26200-b24e-11eb-99b1-99e5682611af.png">
3. Show the user's profile
<img width="350" alt="Screenshot 2021-05-11 at 11 49 37" src="https://user-images.githubusercontent.com/43605864/117796103-0b7f8880-b24f-11eb-86cb-fe004f1478b6.png">

### Expected functionality/enhancement

Maybe a prop called **onLoadComponent** where we could enter a custom component or HTML. This component would appear when the data is being fetched after log-in/mounting of component. 

Desired situation: 
1. Logging in
<img width="350" alt="Screenshot 2021-05-11 at 11 42 13" src="https://user-images.githubusercontent.com/43605864/117795763-c3606600-b24e-11eb-8493-41c2d219c13a.png">
2. Loading data (with custom loading component)

<img width="350" alt="Screenshot 2021-05-11 at 11 49 37"  src="https://user-images.githubusercontent.com/43605864/117797057-eb9c9480-b24f-11eb-8f39-bda018db37b2.png">

3. Show the user's profile
<img width="350" alt="Screenshot 2021-05-11 at 11 49 37" src="https://user-images.githubusercontent.com/43605864/117796103-0b7f8880-b24f-11eb-86cb-fe004f1478b6.png">
### Actual functionality/enhancement

Right now the message "fetching data..."  appears while it loads the information from the user, which is not stylable. Being able to use custom components while loading can make the UI a little bit clear ( ex. a small loading icon ). 
It would also help non-english speaking users understand what is happening. 

I can't seem to find any information about this anywhere. I believe I'm in the right place to ask for such a feature, my apologies if I'm wrong.

**Comment by nicolasmondada** [comment]
Hi @julienmenten ,

Thanks for your detailed suggestion. This custom loading component is in our backlog but it hasn't been scheduled yet. The good thing is it's pretty much aligned with what you described. 

We'll keep this issue updated as we move along.

Cheers,
Nick.-

**Comment by julienmenten** [comment]
Awesome! 
Looking forward to it.
