### ISSUE TITLE
Needs to run with latest React version 17

### ISSUE THREAD

**Issue by SharonStrats** [inrupt/solid-ui-react#421]
### Bug description
When you use either NextJS or create-react-app to start a react project, they use the latest version of React. Then when you install solid-ui-react there is a dependency error.

### To Reproduce
1. npx create-react-app
2. npm i solid-ui-react

### Expected result
I expect that this should work, I have tried a few things but I am having trouble finding a work around at the moment.

### Actual result
I received the error mentioned above.

I don't think the environment is relevant, but I'm on a MacOS just in case.

**Comment by SharonStrats** [comment]
While I believe it should still be on the list to upgrade, I wanted to report that downgrading my node version from 15.4.0 to 12.19.1 allows me to use the library.  Another developer is using 12.22.3 and that works as well.

**Comment by InruptSupport** [comment]
Hi Sharon,

Thanks for reporting this issue. We’ll be looking at this shortly and get back to you.

Thanks,

Inrupt Support

**Comment by InruptSupport** [comment]
Hi Sharon,

Thanks for reporting this issue. We’ll be looking at this shortly and get back to you.

Thanks,

Inrupt Support

**Comment by InruptSupport** [comment]
Hi Sharon,

Thanks for reporting this issue. We’ll be looking at this shortly and get back to you.

Thanks,

Inrupt Support

**Comment by InruptSupport** [comment]
Hi Sharon,

Thanks for reporting this issue. We’ll be looking at this shortly and get back to you.

Thanks,

Inrupt Support

**Comment by InruptSupport** [comment]
Hi Sharon,

Thanks for reporting this issue. We’ll be looking at this shortly and get back to you.

Thanks,

Inrupt Support

**Comment by InruptSupport** [comment]
Hi Sharon,

Thanks for reporting this issue. We’ll be looking at this shortly and get back to you.

Thanks,

Inrupt Support

**Comment by Vinnl** [comment]
@InruptSupport (/ @nicolasmondada?) I submitted a PR with a fix here: https://github.com/inrupt/solid-ui-react/pull/423

**Comment by nicolasmondada** [comment]
Awesome! Thanks Vinnie!!!

**Comment by andydavison** [comment]
Hi @SharonStrats - this should now be fixed in the latest release of solid-ui-react (2.4.1)

And thanks @Vinnl for the PR 😄
