### ISSUE TITLE
webpack_require not a function TypeError

### ISSUE THREAD

**Issue by SharonStrats** [inrupt/solid-ui-react#427]
<img width="1179" alt="Screen Shot 2021-08-19 at 5 15 47 pm" src="https://user-images.githubusercontent.com/9412507/130024858-e858fd99-498d-4e05-8750-7d7f80196a31.png">

**Comment by andydavison** [comment]
@SharonStrats Thanks for raising this! This should be resolved in the latest release, `2.4.2`
