### ISSUE TITLE
FileUpload can't be imported

### ISSUE THREAD

**Issue by LucasnDomingues** [inrupt/solid-ui-react#440]
Hey people, I was looking into your doc, and I noticed you have this component FileUpload (https://solid-ui-react.docs.inrupt.com/?path=/docs/components-fileupload--basic-example). But when I try to import it into my code, it says it's not able to find. I noticed as well that in your code you've developed it, but it's not on the export map.
Could you help me use it please?

I'm using     "@inrupt/solid-ui-react": "^2.4.2",

**Comment by andydavison** [comment]
Hi @LucasnDomingues 

Thanks for raising this! This was indeed an oversight that has now been fixed — the FileUpload component has been exported in the latest 2.5.0 release.
