### ISSUE TITLE
Storybook Provider and Component examples broken

### ISSUE THREAD

**Issue by zg009** [inrupt/solid-ui-react#790]
### Search terms you've used

I didn't use any search terms but looked through the open issues, and didn't find anything addressing this directly.

### Bug description

Visiting any of the links similar to https://solid-ui-react.docs.inrupt.com/?path=/story/components-link--with-children under components or Providers is broken and doesn't render an example.

### To Reproduce
1. Navigate to the link above in any browser

### Expected result

Visible examples of how to use the components

### Actual result

The examples are broken due to webpack modules or nonexistent objects.

**Comment by NSeydoux** [comment]
Hi @zg009 . We are now deprecating the React SDK, so unfortunately we will not be addressing the open issues.
